// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var WebGLVisualizer;
  return WebGLVisualizer = (function() {
    function WebGLVisualizer(_arg, ui, config) {
      var THREE, document, window;
      window = _arg.window, document = _arg.document, THREE = _arg.THREE;
      this.ui = ui;
      if (config == null) {
        config = {};
      }
      this.container = document.createElement('div');
      document.body.appendChild(this.container);
      this.scene = new THREE.Scene;
      this.camera = new THREE.PerspectiveCamera(config.fov || 70.0, window.innerWidth / window.innerHeight, config.near || 1.0, config.far || 10000.0);
      this.scene.add(this.camera);
      this.renderer = new THREE.WebGLRenderer;
      this.renderer.setSize(window.innerWidth, window.innerHeight);
      this.renderer.setClearColor(config.clearColor || 0x000000, config.clearAlpha || 1);
      this.container.appendChild(this.renderer.domElement);
    }

    return WebGLVisualizer;

  })();
});
