// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var WebGLVisualizer;
  return WebGLVisualizer = (function() {
    function WebGLVisualizer(_arg, ui, config) {
      var THREE, document;
      document = _arg.document, THREE = _arg.THREE;
      this.ui = ui;
      this.container = document.createElement('div');
      document.body.appendChild(this.container);
    }

    return WebGLVisualizer;

  })();
});
