// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(['./existance.js', './motion.js', './gravitation.js', './collision.js'], function(Existance, Motion, Gravitation, Collision) {
  return {
    Existance: Existance,
    Motion: Motion,
    Gravitation: Gravitation,
    Collision: Collision
  };
});
