// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var Collision;
  return Collision = (function() {
    function Collision() {}

    return Collision;

  })();
});
