// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var Existance;
  return Existance = (function() {
    function Existance() {}

    return Existance;

  })();
});
