// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var Existance;
  return Existance = (function() {
    function Existance(_arg) {
      this.THREE = _arg.THREE;
      this.name = 'existance';
    }

    Existance.prototype.registerActor = function(token, actor) {
      actor.exists = true;
      actor.mass || (actor.mass = 1.0);
      return actor.position || (actor.position = new this.THREE.Vector3(0, 0, 0));
    };

    return Existance;

  })();
});
