// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var Gravitation;
  return Gravitation = (function() {
    function Gravitation() {}

    return Gravitation;

  })();
});
