// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var Motion;
  return Motion = (function() {
    function Motion(_arg) {
      this.THREE = _arg.THREE;
      this.name = 'motion';
    }

    Motion.prototype.registerActor = function(token, actor) {
      actor.moves = true;
      return actor.velocity || (actor.velocity = new this.THREE.Vector3(0, 0, 0));
    };

    Motion.prototype.applyLinear = function(token, actor) {
      var displace;
      displace = actor.velocity.clone();
      displace.multiplyScalar(token.time);
      return actor.position.add(displace);
    };

    return Motion;

  })();
});
