// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var UserInterface;
  return UserInterface = (function() {
    function UserInterface(globals, config) {}

    return UserInterface;

  })();
});
