// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var UserInterface;
  return UserInterface = (function() {
    function UserInterface(globals, config) {
      globals.app.controller('UI', function($scope) {
        return $scope.restart = function() {
          globals.realm.clear();
          return globals.init();
        };
      });
    }

    UserInterface.prototype.registerActor = function(actor) {};

    return UserInterface;

  })();
});
