// Generated by CoffeeScript 1.6.3
require(['three', 'realm/ui/user_interface', 'realm/visualizer/web_g_l_visualizer'], function(three, UserInterface, WebGLVisualizer) {
  var globals, renderer, ui;
  globals = {
    document: document,
    THREE: THREE,
    window: window
  };
  ui = new UserInterface(globals);
  return renderer = new WebGLVisualizer(globals, ui, {
    clearColor: 0x000000,
    clearAlpha: 1,
    fov: 120
  });
});
