// Generated by CoffeeScript 1.6.3
require(['three', 'realm/ui/user_interface', '/js/realm/engines/classical/classical_mechanics.js', 'realm/visualizer/web_g_l_visualizer', '/js/realm/realm.js'], function(three, UserInterface, ClassicalMechanics, WebGLVisualizer, Realm) {
  var exist, globals, realm, renderer, simulator, ui;
  globals = {
    document: document,
    window: window,
    THREE: THREE
  };
  ui = new UserInterface(globals);
  simulator = new ClassicalMechanics(globals, ui, {
    time: 1,
    paused: false
  });
  renderer = new WebGLVisualizer(globals, ui, {
    clearColor: 0xFF0000,
    clearAlpha: 1,
    fov: 120
  });
  realm = new Realm(globals, ui, {
    engine: simulator,
    visualizer: renderer
  });
  exist = function() {
    requestAnimationFrame(exist);
    return realm.exist();
  };
  return exist();
});
