// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var Actor;
  return Actor = (function() {
    function Actor(ui, config) {
      this.ui = ui;
    }

    return Actor;

  })();
});
