// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var Actor;
  return Actor = (function() {
    function Actor(globals, ui, config) {
      var key;
      this.ui = ui;
      this.actor = true;
      for (key in config) {
        this[key] = config[key];
      }
    }

    return Actor;

  })();
});
