// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var Realm;
  return Realm = (function() {
    function Realm(globals, ui, config) {
      this.ui = ui;
      this.paused = false;
      this.ui.realm = this;
      this.engine = config.engine;
      this.visualizer = config.visualizer;
      this.actors = [];
      globals.tools.AsEventGenerator.call(this);
    }

    Realm.prototype.registerActor = function(actor) {
      actor.id = ++this.actor_id_seq;
      actor.groupid = actor.id;
      actor.enabled = true;
      this.actors.push(actor);
      this.engine.registerActor(actor);
      this.visualizer.registerActor(actor);
      this.ui.registerActor(actor);
      return this.notifyHandlers('onInsert', actor);
    };

    Realm.prototype.deleteActor = function(actor) {
      console.log('todo: Realm.deleteActor');
      return this.notifyHandlers('onDelete', actor);
    };

    Realm.prototype.exist = function() {
      this.visualizer.render();
      if (this.paused) {
        return;
      }
      return this.engine.mainloop(this.actors);
    };

    return Realm;

  })();
});
