// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var Realm;
  return Realm = (function() {
    function Realm(globals, ui, config) {
      this.ui = ui;
      this.ui.realm = this;
      this.engine = config.engine;
      this.visualizer = config.visualizer;
      this.actors = [];
    }

    Realm.prototype.registerActor = function(actor) {
      actor.id = ++this.actor_id_seq;
      actor.groupid = actor.id;
      actor.enabled = true;
      this.actors.push(actor);
      this.engine.registerActor(actor);
      this.visualizer.registerActor(actor);
      return this.ui.registerActor(actor);
    };

    Realm.prototype.exist = function() {
      return this.visualizer.render();
    };

    return Realm;

  })();
});
