// Generated by CoffeeScript 1.4.0
var et, gimbal, plex;

plex = require('plex');

et = require('et');

gimbal = require('./gimbal');

module.exports = function(port) {
  var context;
  if (port == null) {
    port = 3000;
  }
  context = plex.start({
    mode: 'proxy',
    connect: {
      adaptor: 'socket.io',
      uri: 'http://localhost:3332'
    },
    listen: {
      adaptor: 'socket.io',
      server: et.al({
        port: port,
        session: false,
        auth: false
      }),
      onConnect: function(edge) {
        return edge.getPublisher()('event:client:start');
      }
    },
    protocol: require('./protocols')
  });
  context.listen.server.use(require('connect-jade')({
    root: __dirname + '/../views'
  }));
  context.listen.server.get('/', function(req, res) {
    return res.render('index');
  });
  return context;
};
