// Generated by CoffeeScript 1.6.3
var root;

require('vertex').create({
  www: {
    listen: {
      port: 3000
    },
    allowRoot: 'true',
    routes: root = function(opts, callback) {
      return callback(null, 'okgood');
    }
  }
});

root.$www = {};
