// Generated by CoffeeScript 1.6.3
var app, express, packager, path;

path = require('path');

express = require('express');

app = express();

packager = new (require('cetera').Packager);

packager.mount({
  app: app,
  name: 'js',
  src: path.join(__dirname, '/client'),
  scripts: ['bundle.js', 'main.js']
});

app.get('/', function(req, res) {
  return res.send("\n<body>\n    <script src=\"/js/bundle.js\"></script>\n    <script src=\"/js/main.js\"></script>\n</body>\n");
});

app.listen(3000);
