// Generated by CoffeeScript 1.4.0
var app, express, gimbal, plex;

express = require('express');

plex = require('plex');

gimbal = require('./gimbal');

app = express();

module.exports = function(port) {
  var context;
  if (port == null) {
    port = 3000;
  }
  app.get('/', function(req, res) {
    return res.send('');
  });
  app.use(gimbal);
  context = plex.start({
    mode: 'proxy',
    connect: {
      adaptor: 'socket.io',
      uri: 'http://localhost:3332'
    },
    listen: {
      adaptor: 'socket.io',
      server: app.listen(port)
    }
  });
  return context.listen.server;
};
