// Generated by CoffeeScript 1.6.3
var home;

module.exports = home = function(opts, callback) {
  return callback(null, {
    headers: {
      'Content-Type': 'text/html'
    },
    body: ''
  });
};

home.$www = {};
