// Generated by CoffeeScript 1.4.0
var MockClient, ioClient;

ioClient = require('socket.io-client');

module.exports = MockClient = (function() {

  function MockClient(port, mode, wait, toCallback) {
    var _this = this;
    setTimeout((function() {
      return toCallback();
    }), wait);
    this.received || (this.received = {});
    this.connection = ioClient.connect("http://localhost:" + port);
    this.connection.on('event:client:start', function(payload) {
      switch (mode) {
        case 'viewport':
          return _this.connection.emit("event:register:viewport");
        case 'controller':
          return _this.connection.emit("event:register:controller", {
            primary_viewport: 'PRIMARY_VIEWPORT_ID',
            input_cube: [640, 400, 0]
          });
      }
    });
    this.connection.on('event:register:viewport:ok', function(payload) {
      return _this.received['event:register:viewport:ok'] = payload;
    });
    this.connection.on('event:register:controller:ok', function(payload) {
      return _this.received['event:register:controller:ok'] = payload;
    });
  }

  MockClient.prototype.send = function(event, payload, wait, callback) {
    this.connection.emit(event, payload);
    return setTimeout((function() {
      return callback();
    }), wait);
  };

  return MockClient;

})();
