// Generated by CoffeeScript 1.4.0
var MockClient, ioClient;

ioClient = require('socket.io-client');

module.exports = MockClient = (function() {

  function MockClient(port, mode, wait, toCallback) {
    var _this = this;
    this.connection = ioClient.connect("http://localhost:" + port);
    this.connection.on('event:client:start', function(payload) {
      return _this.connection.emit("event:register:" + mode, {
        pending: 'DATA'
      });
    });
    setTimeout((function() {
      return toCallback();
    }), wait);
  }

  return MockClient;

})();
