// Generated by CoffeeScript 1.4.0
var MockClient, ioClient;

ioClient = require('socket.io-client');

module.exports = MockClient = (function() {

  function MockClient(port, mode, watchResponseEvent, toCallback) {
    var _this = this;
    this.watchResponseEvent = watchResponseEvent;
    this.toCallback = toCallback;
    this.socket = ioClient.connect("http://localhost:" + port);
    this.socket.on('event:client:start', function(payload) {
      return _this.respond("event:register:" + mode, {
        pending: 'DATA'
      });
    });
  }

  MockClient.prototype.respond = function(event, payload) {
    this.socket.emit(event, payload);
    if (event === this.watchResponseEvent) {
      return this.toCallback();
    }
  };

  return MockClient;

})();
