// Generated by CoffeeScript 1.4.0

module.exports = function(subscribe, publish, edge, context) {
  require('../lib/viewport-protocol')(subscribe, publish, edge, context);
  return require('../lib/controller-protocol')(subscribe, publish, edge, context);
};
