// Generated by CoffeeScript 1.4.0

module.exports = function(subscribe, publish) {
  subscribe('event:register:viewport', function(payload) {
    console.log("received:", 'event:register:viewport', payload);
    return console.log('registering viewport');
  });
  return subscribe('event:register:controller', function(payload) {
    console.log("received:", 'event:register:controller', payload);
    return console.log('registering controller');
  });
};
