// Generated by CoffeeScript 1.4.0

module.exports = function(subscribe, publish, edge, context) {
  subscribe('request:socket:disconnect', function(payload) {
    console.log('RECEIVED: request:socket:disconnect from: ', edge.localId());
    return edge.connection.disconnect();
  });
  require('../lib/viewport-protocol')(subscribe, publish, edge, context);
  return require('../lib/controller-protocol')(subscribe, publish, edge, context);
};
