// Generated by CoffeeScript 1.4.0

module.exports = function(subscribe, publish, edge, context) {
  return subscribe('event:register:viewport', function(payload) {
    var _base;
    console.log("REGISTER VIEWPORT ", edge.localId());
    context.gimbal || (context.gimbal = {});
    (_base = context.gimbal).viewports || (_base.viewports = {});
    return context.gimbal.viewports[edge.localId()] = edge;
  });
};
