// Generated by CoffeeScript 1.4.0
var os, qrCode;

os = require('os');

qrCode = require('qrcode-npm');

module.exports = function(subscribe, publish, edge, context) {
  return subscribe('event:register:viewport', function(payload) {
    var connectSpec, details, iface, ifaces, imageTag, qr, url, _base, _i, _len, _ref;
    context.gimbal || (context.gimbal = {});
    (_base = context.gimbal).viewports || (_base.viewports = {});
    context.gimbal.viewports[edge.localId()] = edge;
    url = context.listen.server.url;
    if (url.match(/\/\/0\.0\.0\.0/)) {
      ifaces = os.networkInterfaces();
      for (iface in ifaces) {
        _ref = ifaces[iface];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          details = _ref[_i];
          if (details.internal) {
            continue;
          }
          if (details.family !== 'IPv4') {
            continue;
          }
          if (details.address.match(/^192\.168\./)) {
            continue;
          }
          url = url.replace('0.0.0.0', details.address);
        }
      }
      if (url.match(/\/\/0\.0\.0\.0/)) {
        throw 'could not find wifi LAN ip';
      }
    }
    connectSpec = "" + url + " " + (edge.localId());
    qr = qrCode.qrcode(3, 'L');
    qr.addData(connectSpec);
    qr.make();
    imageTag = qr.createImgTag(3);
    return publish('event:register:viewport:ok', imageTag);
  });
};
