// Generated by CoffeeScript 1.4.0

module.exports = function(subscribe, publish, edge, context) {
  console.log('TODO: switch these to ../lib/.. before release');
  require('../src/viewport-protocol')(subscribe, publish, edge, context);
  return require('../src/controller-protocol')(subscribe, publish, edge, context);
};
