// Generated by CoffeeScript 1.6.3
var readFileSync, root;

readFileSync = require('fs').readFileSync;

root = function(opts, callback) {
  return callback(null, {
    statusCode: 301,
    headers: {
      location: '/viewport'
    }
  });
};

root.bundle = function(opts, callback) {
  return callback(null, {
    headers: {
      'Content-Type': 'text/javascript'
    },
    body: readFileSync("" + __dirname + "/../bundle.js")
  });
};

root.$www = {};

root.bundle.$www = {};

root.viewport = require('./viewport');

root.controller = require('./controller');

module.exports = root;
