// Generated by CoffeeScript 1.6.3
var root;

module.exports = root = function(opts, callback) {
  return callback(null, {
    statusCode: 301,
    headers: {
      location: '/home'
    }
  });
};

root.$www = {};

root.home = require('./home');
