// Generated by CoffeeScript 1.6.3
var viewport;

module.exports = viewport = function(opts, callback) {
  return callback(null, {
    headers: {
      'Content-Type': 'text/html'
    },
    body: "<body>\n\n    <script src=\"./build\"> </script>\n    <script src=\"./controller\"> </script>\n\n</body>"
  });
};

viewport.$www = {};
