// Generated by CoffeeScript 1.6.3
var viewport;

module.exports = viewport = function(opts, callback) {
  return callback(null, {
    headers: {
      'Content-Type': 'text/html'
    },
    body: "<body>\n    <style>\n    body {\n        background-color: green;\n    }\n    </style>\n    <script src=\"./controller\"></script>\n</body>"
  });
};

viewport.$www = {};
