// Generated by CoffeeScript 1.6.3
var define,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(['../realm/actor.js'], function(Actor) {
  var HudVisible;
  return HudVisible = (function(_super) {
    __extends(HudVisible, _super);

    function HudVisible(globals, ui, config) {
      this.ui = ui;
      HudVisible.__super__.constructor.call(this, globals, this.ui, config);
      this.hudvisible = true;
    }

    return HudVisible;

  })(Actor);
});
