// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(['./boundary_sphere.js', './spherical_mass.js'], function(BoundarySphere, SphericalMass) {
  return {
    BoundarySphere: BoundarySphere,
    SphericalMass: SphericalMass
  };
});
