// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  return function(name) {
    return this[name] = {
      name: name,
      set: function(nextState) {
        if (this.get === null) {
          this.get = nextState;
          this.delta = nextState;
          return;
        }
        if (this.get === nextState) {
          this.changed = false;
          this.delta = 0;
          return;
        }
        this.delta = nextState - this.get;
        this.get = nextState;
        this.changed = true;
      },
      get: null,
      changed: false
    };
  };
});
