// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  return function() {
    var _this = this;
    this.handlers = [];
    this.registerHandler = function(handler) {
      return _this.handlers.push(handler);
    };
    return this.notifyHandlers = function(event, object) {
      var handler, _i, _len, _ref, _results;
      _ref = _this.handlers;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        handler = _ref[_i];
        if (typeof handler[event] !== 'function') {
          continue;
        }
        _results.push(handler[event].call(handler, object));
      }
      return _results;
    };
  };
});
