// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  return function() {
    var _this = this;
    this.handlers = [];
    return this.registerHandler = function(handler) {
      return _this.handlers.push(handler);
    };
  };
});
