// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  return function(indexname, fn) {
    this[indexname] = {
      index: [],
      "function": fn
    };
    if (this.pair == null) {
      this.pair = {
        _self: this
      };
    }
    this.get_indexed = function(pass_through, indX, index, version, a, b) {
      var previous;
      if (indX[a.id] == null) {
        indX[a.id] = [];
      }
      if (indX[a.id][b.id] == null) {
        indX[a.id][b.id] = [version, this[index]["function"](pass_through, a, b)];
        return indX[a.id][b.id][1];
      }
      previous = indX[a.id][b.id];
      if (previous[0] === version) {
        return previous[1];
      }
      indX[a.id][b.id] = [version, this[index]["function"](pass_through, a, b, previous[1])];
      return indX[a.id][b.id][1];
    };
    return this.pair[indexname] = function(pass_through, version, a, b) {
      return this._self.get_indexed(pass_through, this._self[indexname].index, indexname, version, a, b);
    };
  };
});
