// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  return function(storename) {
    if (typeof this[storename] === 'undefined') {
      this['AsNamedStore_' + storename] = [];
      this[storename] = {};
    }
    return this['create_' + storename] = function(name, value) {
      var i;
      i = this['AsNamedStore_' + storename].push([name, value]);
      return this[storename][name] = this['AsNamedStore_' + storename][i - 1][1];
    };
  };
});
