// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(['./as_event_generator.js', './as_just_in_time.js'], function(AsEventGenerator, AsJustInTime) {
  return {
    AsEventGenerator: AsEventGenerator,
    AsJustInTime: AsJustInTime
  };
});
