// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(['./as_event_generator.js'], function(AsEventGenerator) {
  return {
    AsEventGenerator: AsEventGenerator
  };
});
