// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(['./as_event_generator.js', './as_just_in_time.js', './as_state.js', './as_delta_state.js', './as_collision_detector.js'], function(AsEventGenerator, AsJustInTime, AsState, AsDeltaState, AsCollisionDetector) {
  return {
    AsEventGenerator: AsEventGenerator,
    AsJustInTime: AsJustInTime,
    AsState: AsState,
    AsDeltaState: AsDeltaState,
    AsCollisionDetector: AsCollisionDetector(AsJustInTime, AsState)
  };
});
