// Generated by CoffeeScript 1.6.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var ClassicalMechanics;
  return ClassicalMechanics = (function() {
    function ClassicalMechanics(globals, ui, config) {
      this.ui = ui;
      if (config == null) {
        config = {};
      }
      this.token = {
        cycle: 0,
        time: config.time || 1.0,
        paused: config.paused || false,
        count: 0,
        actors: null
      };
      this.ui.token = this.token;
    }

    return ClassicalMechanics;

  })();
});
